# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: List Xcode installations
      run: sudo ls -1 /Applications | grep "Xcode"
    - name: Select Xcode 15.3
      run: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
    - name: Build
      run: swift build --target OwlKitTests
    - name: Run tests
      run: swift test
  
  build-ubuntu:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build --target OwlKitTests
    - name: Run tests
      run: swift test